export const FETCH_ITEMS = "FETCH ITEMS";
export const ADD_ITEM = "ADD ITEM";
export const REMOVE_ITEM = "REMOVE ITEM";

export const ADD_ITEM_TO_CURRENT_LIST = "ADD ITEM TO CURRENT LIST";
export const REMOVE_ITEM_FROM_CURRENT_LIST = "REMOVE ITEM FROM CURRENT LIST";
export const DECREASE_QUANTITY = "DECREASE QUANTITY";
export const INCREASE_QUANTITY = "INCREASE QUANTITY";
export const CLEAR_CURRENT_LIST = "CLEAR CURRENT LIST";
export const ADD_NAME_SAVE = " ADD NAME SAVE";

export const FETCH_CATEGORIES = "FETCH CATEGORIES";
export const ADD_ITEM_TO_CATEGORIES = "ADD ITEM TO CATEGORIES";
export const DELETE_ITEM_FROM_CATEGORIES = "DELETE ITEM FROM CATEGORIES";

export const FETCH_LISTS = "FETCH LISTS";
